Repository PLAID-lib/plaid, pull requests merged in 2025-08, with the labels that each got.

#135 🐛 fix(docs) correct doc compilation
  .readthedocs.yml
  CHANGELOG.md
  docs/conf.py
  docs/source/notebooks/metrics.ipynb
  src/plaid/bridges/huggingface_bridge.py
Labels: documentation

#101 🎉 Pipeline formalization, including scikit-learn block wrappers
  CHANGELOG.md
  docs/conf.py
  docs/index.rst
  docs/refs.bib
  docs/source/citation.md
  docs/source/contributing.md
  docs/source/description.md
  docs/source/notebooks.rst
  docs/source/notebooks/config_pipeline.yml
  docs/source/notebooks/init_with_tabular.ipynb
  docs/source/notebooks/interpolation.ipynb
  docs/source/notebooks/pipeline.ipynb
  docs/source/plaid_benchmarks.rst
  docs/source/quickstart.md
  environment.yml
  examples/pipelines/pipeline.py
  examples/run_examples.sh
  pyproject.toml
  src/plaid/bridges/huggingface_bridge.py
  src/plaid/constants.py
  src/plaid/containers/dataset.py
  src/plaid/containers/sample.py
  src/plaid/containers/utils.py
  src/plaid/pipelines/__init__.py
  src/plaid/pipelines/plaid_blocks.py
  src/plaid/pipelines/sklearn_block_wrappers.py
  src/plaid/types/__init__.py
  src/plaid/types/cgns_types.py
  src/plaid/types/feature_types.py
  src/plaid/types/sklearn_types.py
  src/plaid/utils/base.py
  tests/bridges/test_huggingface_bridge.py
  tests/conftest.py
  tests/containers/test_dataset.py
  tests/containers/test_sample.py
  tests/containers/test_utils.py
  tests/pipelines/conftest.py
  tests/pipelines/test_blocks.py
  tests/pipelines/test_plaid_blocks.py
  tests/pipelines/test_sklearn_block_wrappers.py
Labels: documentation, enhancement, ci

#147 ♻️ fix(docs) tricks to correct sphinx warning - some remain, but the aut…
  src/plaid/bridges/_huggingface_helpers.py
  src/plaid/bridges/huggingface_bridge.py
  src/plaid/types/feature_types.py
  src/plaid/utils/split.py
Labels: bug, documentation, enhancement

#156 ♻️ Fix typing + Ruff on benchmarks
  benchmarks/FNO/2D_ElPlDynamics/utils.py
  benchmarks/MGN/configs.py
  benchmarks/MGN/data.py
  benchmarks/MGN/main.py
  benchmarks/MGN/main_2d_elasto_ddp.py
  benchmarks/MGN/model.py
  benchmarks/MGN/train.py
  benchmarks/MGN/utils.py
  benchmarks/MMGP/2D_profile/launch_morphings.py
  benchmarks/MMGP/2D_profile/model.py
  benchmarks/MMGP/2D_profile/utils_2dprofile.py
  benchmarks/MMGP/Rotor37/run_rotor37.py
  benchmarks/MMGP/VKI-LS59/AM_POD.py
  benchmarks/MMGP/VKI-LS59/VKI_study.ipynb
  benchmarks/MMGP/VKI-LS59/data.py
  benchmarks/MMGP/VKI-LS59/model.py
  benchmarks/MMGP/VKI-LS59/processor.py
  benchmarks/MMGP/VKI-LS59/utils.py
  benchmarks/Vi-Transf/main_elasto_plasto_dynamics.py
  benchmarks/Vi-Transf/main_stationary.py
  benchmarks/Vi-Transf/src/data/loader/bridges/airfrans_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/bridges/base_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/bridges/elasto_plasto_dynamics.py
  benchmarks/Vi-Transf/src/data/loader/bridges/multiscale_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/bridges/no_bridge.py
  benchmarks/Vi-Transf/src/data/loader/bridges/profile_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/bridges/rotor_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/bridges/tensile_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/bridges/utils.py
  benchmarks/Vi-Transf/src/data/loader/bridges/vki_sample_to_geometric.py
  benchmarks/Vi-Transf/src/data/loader/hub_loader.py
  benchmarks/Vi-Transf/src/data/loader/loader.py
  benchmarks/Vi-Transf/src/data/scaler.py
  benchmarks/Vi-Transf/src/data/utils.py
  benchmarks/Vi-Transf/src/evaluation/submission.py
  benchmarks/Vi-Transf/src/models/model.py
  benchmarks/Vi-Transf/src/models/vits/flatformer_cls_less.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/flatten_data_tokenizers.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/flatten_tokenizer.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/morton.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/partitioners/metis_partitioner.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/partitioners/partitioner.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/temporal_flatten_tokenizer.py
  benchmarks/Vi-Transf/src/models/vits/tokenization/tokenizer.py
  examples/containers/dataset_example.py
  examples/containers/sample_example.py
  examples/pipelines/pipeline.py
  examples/post/bisect_example.py
  examples/post/metrics_example.py
  examples/problem_definition_example.py
  examples/wrappers/environment.yml
  examples/wrappers/mmgp_pipeline.py
  examples/wrappers/sklearn_example.py
  src/plaid/containers/sample.py
  src/plaid/post/bisect.py
  src/plaid/types/cgns_types.py
  src/plaid/types/feature_types.py
  src/plaid/utils/interpolation.py
  src/plaid/utils/stats.py
Labels: enhancement, typing
